#!/bin/bash
# Refresh the LOOP section of /var/lib/shared/STATE.md so every Bob session
# opens with live awareness of the Workloft Loop board.
#
# Block markers:
#   <!-- LOOP:BEGIN -->
#   …auto-generated by gary/loop_board.py…
#   <!-- LOOP:END -->
#
# Anything outside the markers is human-curated and never touched.
set -eu

STATE_FILE=/var/lib/shared/STATE.md
LOCK=/tmp/refresh-loop-in-state.lock
TMP_BLOCK=$(mktemp /tmp/loop-state-block.XXXX.md)
trap 'rm -f "$TMP_BLOCK"' EXIT

exec 9>"$LOCK"
flock -n 9 || exit 0

mkdir -p "$(dirname "$STATE_FILE")"
[ -f "$STATE_FILE" ] || { echo "# STATE.md" > "$STATE_FILE"; chmod 644 "$STATE_FILE"; }

{
    echo "<!-- LOOP:BEGIN -->"
    /usr/bin/python3 /home/workloft/gary/loop_board.py board
    echo
    echo "> Loop pilot is the #loop tag in Gary. Bob: pull from this board, transition to in_progress when starting, exit in SHIPPED/BLOCKED/KILLED only."
    echo "> CLI: \`gary list --tag loop\` · \`gary start <id>\` · \`gary block <id> --reason …\` · \`gary kill <id> --reason …\`"
    echo "<!-- LOOP:END -->"
} > "$TMP_BLOCK"

python3 - "$STATE_FILE" "$TMP_BLOCK" <<'PYEOF'
import re, sys, pathlib
state_path, block_path = sys.argv[1], sys.argv[2]
state = pathlib.Path(state_path).read_text(encoding="utf-8")
block = pathlib.Path(block_path).read_text(encoding="utf-8").rstrip() + "\n"
if "<!-- LOOP:BEGIN -->" in state:
    new = re.sub(
        r"<!-- LOOP:BEGIN -->.*?<!-- LOOP:END -->",
        block.rstrip(), state, count=1, flags=re.DOTALL,
    )
else:
    if not state.endswith("\n"):
        state += "\n"
    new = state + "\n" + block
pathlib.Path(state_path).write_text(new, encoding="utf-8")
PYEOF
